import { jsPDF } from 'jspdf';
import { format, parse } from 'date-fns';

interface PDFEntry {
  id: string;
  amount: number;
  type: string;
  remark: string;
  payment_mode: string;
  entry_date: string;
  entry_time: string;
  attachments?: any[];
}

export const generatePDF = (
  bookName: string,
  entries: PDFEntry[],
  userName: string = 'User'
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let yPosition = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${bookName}'s Business Report`, margin, yPosition);
  
  yPosition += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const currentDate = format(new Date(), 'dd MMM yyyy, h:mm a');
  doc.text(`Generated On - ${currentDate}. Generated by - ${userName}`, margin, yPosition);

  yPosition += 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(bookName, margin, yPosition);

  // Calculate date range
  if (entries.length > 0) {
    const sortedEntries = [...entries].sort((a, b) => 
      new Date(a.entry_date).getTime() - new Date(b.entry_date).getTime()
    );
    const startDate = format(new Date(sortedEntries[0].entry_date), 'dd MMM yyyy');
    const endDate = format(new Date(sortedEntries[sortedEntries.length - 1].entry_date), 'dd MMM yyyy');
    
    yPosition += 10;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Duration: ${startDate} - ${endDate}`, margin, yPosition);
  }

  // Calculate totals
  const totalCashIn = entries
    .filter(e => e.type === 'cash_in')
    .reduce((sum, e) => sum + Number(e.amount), 0);
  const totalCashOut = entries
    .filter(e => e.type === 'cash_out')
    .reduce((sum, e) => sum + Number(e.amount), 0);
  const finalBalance = totalCashIn - totalCashOut;

  // Summary boxes
  yPosition += 15;
  const boxWidth = (pageWidth - 2 * margin - 8) / 3;
  const boxHeight = 20;

  // Total Cash In box
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, yPosition, boxWidth, boxHeight, 'F');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Total Cash in', margin + 3, yPosition + 6);
  doc.setFontSize(14);
  doc.setTextColor(34, 197, 94);
  doc.setFont('helvetica', 'bold');
  doc.text(totalCashIn.toLocaleString(), margin + 3, yPosition + 14);

  // Total Cash Out box
  doc.setFillColor(240, 240, 240);
  doc.rect(margin + boxWidth + 4, yPosition, boxWidth, boxHeight, 'F');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'normal');
  doc.text('Total Cash out', margin + boxWidth + 7, yPosition + 6);
  doc.setFontSize(14);
  doc.setTextColor(239, 68, 68);
  doc.setFont('helvetica', 'bold');
  doc.text(totalCashOut.toLocaleString(), margin + boxWidth + 7, yPosition + 14);

  // Final Balance box
  doc.setFillColor(240, 240, 240);
  doc.rect(margin + 2 * boxWidth + 8, yPosition, boxWidth, boxHeight, 'F');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'normal');
  doc.text('Final Balance', margin + 2 * boxWidth + 11, yPosition + 6);
  doc.setFontSize(14);
  doc.setTextColor(finalBalance >= 0 ? 34 : 239, finalBalance >= 0 ? 197 : 68, finalBalance >= 0 ? 94 : 68);
  doc.setFont('helvetica', 'bold');
  doc.text(finalBalance.toLocaleString(), margin + 2 * boxWidth + 11, yPosition + 14);

  // Entries table
  yPosition += 30;
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total No. of entries: ${entries.length}`, margin, yPosition);

  yPosition += 8;
  
  // Table headers with attachments column
  const colWidths = {
    date: 22,
    remark: 40,
    attachments: 18,
    mode: 18,
    cashIn: 22,
    cashOut: 22,
    balance: 22
  };

  doc.setFillColor(245, 245, 245);
  doc.rect(margin, yPosition, pageWidth - 2 * margin, 8, 'F');
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Date', margin + 2, yPosition + 5);
  doc.text('Remark', margin + colWidths.date + 2, yPosition + 5);
  doc.text('Attach', margin + colWidths.date + colWidths.remark + 2, yPosition + 5);
  doc.text('Mode', margin + colWidths.date + colWidths.remark + colWidths.attachments + 2, yPosition + 5);
  doc.text('Cash in', margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + 2, yPosition + 5);
  doc.text('Cash out', margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + colWidths.cashIn + 2, yPosition + 5);
  doc.text('Balance', margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + colWidths.cashIn + colWidths.cashOut + 2, yPosition + 5);

  yPosition += 8;

  // Table rows
  doc.setFont('helvetica', 'normal');
  let runningBalance = 0;

  const sortedEntries = [...entries].sort((a, b) => {
    const dateA = new Date(`${a.entry_date}T${a.entry_time}`);
    const dateB = new Date(`${b.entry_date}T${b.entry_time}`);
    return dateA.getTime() - dateB.getTime();
  });

  sortedEntries.forEach((entry, index) => {
    const entryDate = format(new Date(entry.entry_date), 'dd MMM yy');
    const hasAttachments = entry.attachments && entry.attachments.length > 0;
    const attachmentCount = hasAttachments ? entry.attachments.length : 0;
    
    // Update running balance
    if (entry.type === 'cash_in') {
      runningBalance += Number(entry.amount);
    } else {
      runningBalance -= Number(entry.amount);
    }

    // Calculate remark text with word wrapping
    const remarkText = entry.remark || '';
    const maxRemarkWidth = colWidths.remark - 4;
    const remarkLines = doc.splitTextToSize(remarkText, maxRemarkWidth);
    const rowHeight = Math.max(8, remarkLines.length * 4 + 2);

    // Check if we need a new page
    if (yPosition + rowHeight > 270) {
      doc.addPage();
      yPosition = 20;
    }

    // Date
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(entryDate, margin + 2, yPosition + 5);

    // Remark with word wrapping
    doc.text(remarkLines, margin + colWidths.date + 2, yPosition + 5);

    // Attachments column with clickable icons
    if (hasAttachments) {
      doc.setTextColor(59, 130, 246); // Blue color for icon
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      
      // Show multiple icons if there are multiple attachments
      const iconsToShow = Math.min(attachmentCount, 3);
      for (let i = 0; i < iconsToShow; i++) {
        const iconX = margin + colWidths.date + colWidths.remark + 2 + (i * 5);
        
        // Draw a small rectangle to represent an image
        doc.setFillColor(59, 130, 246);
        doc.rect(iconX, yPosition + 1.5, 3, 3, 'F');
        
        // Add [IMG] text
        doc.setFontSize(6);
        doc.text('IMG', iconX, yPosition + 6);
        
        // Make the icon clickable if URL exists
        if (entry.attachments[i]?.url) {
          let fullUrl = entry.attachments[i].url;
          // If URL doesn't start with http:// or https://, prepend Supabase storage base URL
          if (!fullUrl.startsWith('http://') && !fullUrl.startsWith('https://')) {
            fullUrl = `https://htnaynrszuxazqyosnzl.supabase.co/storage/v1/object/public/entry-attachments/${fullUrl}`;
          }
          doc.link(iconX, yPosition + 1, 3, 5, { url: fullUrl });
        }
      }
      
      // If more than 3 attachments, show count
      if (attachmentCount > 3) {
        doc.setFontSize(7);
        doc.text(`+${attachmentCount - 3}`, margin + colWidths.date + colWidths.remark + 17, yPosition + 5);
      }
      
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
    }

    // Mode
    doc.text(entry.payment_mode || 'Cash', margin + colWidths.date + colWidths.remark + colWidths.attachments + 2, yPosition + 5);

    // Cash In
    if (entry.type === 'cash_in') {
      doc.setTextColor(34, 197, 94);
      doc.text(entry.amount.toLocaleString(), margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + 2, yPosition + 5);
      doc.setTextColor(0, 0, 0);
    }

    // Cash Out
    if (entry.type === 'cash_out') {
      doc.setTextColor(239, 68, 68);
      doc.text(entry.amount.toLocaleString(), margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + colWidths.cashIn + 2, yPosition + 5);
      doc.setTextColor(0, 0, 0);
    }

    // Balance
    doc.setTextColor(runningBalance >= 0 ? 0 : 239, 0, runningBalance >= 0 ? 0 : 68);
    doc.text(runningBalance.toLocaleString(), margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + colWidths.cashIn + colWidths.cashOut + 2, yPosition + 5);
    doc.setTextColor(0, 0, 0);

    yPosition += rowHeight;

    // Draw row separator
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
  });

  // Final balance row
  if (yPosition > 260) {
    doc.addPage();
    yPosition = 20;
  }
  
  yPosition += 8;
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, yPosition, pageWidth - 2 * margin, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text(format(new Date(), 'dd MMM yy'), margin + 2, yPosition + 5);
  doc.text('Final Balance', margin + colWidths.date + 2, yPosition + 5);
  doc.setTextColor(finalBalance >= 0 ? 0 : 239, 0, finalBalance >= 0 ? 0 : 68);
  doc.text(finalBalance.toLocaleString(), margin + colWidths.date + colWidths.remark + colWidths.attachments + colWidths.mode + colWidths.cashIn + colWidths.cashOut + 2, yPosition + 5);

  // Save PDF
  const fileName = `${bookName}_Report_${format(new Date(), 'dd-MMM-yyyy')}.pdf`;
  doc.save(fileName);
};
